### ISSUE TITLE
Spawner failed to start [status=1].

### ISSUE THREAD

**Issue by kedarisharath** [jupyterhub/systemdspawner#66]
[I 2020-01-22 12:44:47.298 JupyterHub spawner:1417] Spawning jupyterhub-singleuser --port=40287
Failed to set groups [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/home/sharatkedari/anaconda3/bin/jupyterhub-singleuser", line 5, in <module>
    from jupyterhub.singleuser import main
  File "/home/sharatkedari/anaconda3/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 41, in <module>
    from notebook.notebookapp import (
  File "/home/sharatkedari/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 40, in <module>
    ioloop.install()
  File "/home/sharatkedari/anaconda3/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'
[I 2020-01-22 12:44:48.254 JupyterHub log:174] 302 GET /hub/spawn -> /hub/spawn-pending/sharatkedari (sharatkedari@10.240.110.179) 1006.68ms
[I 2020-01-22 12:44:48.278 JupyterHub pages:347] sharatkedari is pending spawn
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /home/sharatkedari/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py:741> exception=HTTPError()>
Traceback (most recent call last):
  File "/home/sharatkedari/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 939, in spawn_single_user
    timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sharatkedari/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 972, in spawn_single_user
    % (status, spawner._log_name),
tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=1]. The logs for sharatkedari may contain details.)

**Comment by whositwhatnow** [comment]
Having same issue, did you ever find out a fix for this?

**Comment by consideRatio** [comment]
```
Failed to set groups [Errno 1] Operation not permitted
```

Was jupyterhub not started as the root user? I think that is a requirement for systemdspawner.

Closing, presuming that was the issue.
